name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          python3 -m pytest -v --junitxml=results.xml
        env:
          API_KEY: ${{secrets.MOVIE_API_KEY}}

      - name: Artifact results.xml
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: results.xml
          path: results.xml

      # - name: Test with pytest
      #   run: |
      #     API_KEY='4f8defcdf72c5c16da47804eacfaf7a1' python3 -m pytest --log-cli-level=INFO -v -s --junitxml=results.xml